version: "3"

services:
  docusaurus:
    build: .
    network_mode: "host"
    volumes:
      - ./docs:/app/docs
      - ./src:/app/src
      - ./static:/app/static
      - ./docusaurus.config.js:/app/docusaurus.config.js
      - ./sidebars.js:/app/sidebars.js
    working_dir: /app/
