# .github/workflows/deploy.yml

# name: github pages

# on:
#  push:
#    branches:
#      - master
#    paths:
#      - '.github/workflows/deploy.yml'
#      - 'website/**'

# jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: website
#    steps:
#      - uses: actions/checkout@v2

#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'

#      - name: Get yarn cache
#        id: yarn-cache
#        run: echo "::set-output name=dir::$(yarn cache dir)"

#      - name: Cache dependencies
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache.outputs.dir }}
#          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-website-

#      - run: yarn install --frozen-lockfile
#      - run: yarn build
#      - run: npm run check-links

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./website/build
